name: Run Python
on: 
    push: 
jobs: 
    build: 
        name: set and run
        runs-on: ubunt-latest
        steps: 
            - uses: action/checjout@v2
            - name: step1
              run: 
                python3 main.py